[phases.setup]
nixPkgs = ["python3", "ffmpeg", "git", "gcc"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "ffmpeg -version"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"
